using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace ZRQ.WPF.DataGridSample.GroupSample
{
    /// <summary>
    /// Interaction logic for DataGroupWindow.xaml
    /// </summary>
    public partial class DataGroupWindow : Window
    {
        CollectionView? myView = null;
        DataGroupViewModel viewModel;

        public DataGroupWindow()
        {
            InitializeComponent();
            viewModel = new DataGroupViewModel();
            this.DataContext = viewModel;
        }
        private void AddGrouping(object sender, RoutedEventArgs e)
        {
            myView = (CollectionView)CollectionViewSource.GetDefaultView(dg_GroupSample.ItemsSource);
            if (myView.CanGroup == true)
            {
                PropertyGroupDescription groupDescription
                    = new PropertyGroupDescription(nameof(DataGroupModel.GroupName));
                myView.GroupDescriptions.Add(groupDescription);

                dgCol_ResultValue.Visibility = Visibility.Hidden;
            }
            else
            {
                return;
            }
        }

        private void RemoveGrouping(object sender, RoutedEventArgs e)
        {
            myView = (CollectionView)CollectionViewSource.GetDefaultView(dg_GroupSample.ItemsSource);
            myView.GroupDescriptions.Clear();
            dgCol_ResultValue.Visibility = Visibility.Visible;
        }

        private void dg_GroupSample_AutoGeneratedColumns(object sender, EventArgs e)
        {

        }

        private void dg_GroupSample_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {

        }
    }
}
